# Generated by Django 5.0.3 on 2024-04-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payment_method',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
